spring:
  mvc:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
  devtools:
    livereload:
      enabled: true
  datasource:
    jndi-name: jdbc/rookie
  servlet:
    multipart:
      enabled: true
      location: C:/yoons_world/files
      max-file-size: 10MB
      max-request-size: 30MB
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:mappers/*.xml
  
  
server:
  servlet:
    session:
      timeout: 180m

    encoding:
      charset: UTF-8
      force: true
      
  error:
    path: /error 
---
spring:
  config:
    activate:
      on-profile: dev
realpath: \home\yoons\files
deletedpath: \home\yoons\deletedfiles
---
spring:
  config:
    activate:
      on-profile: loc
realpath: C:/yoons_world/files
deletedpath: C:/yoons_world/deletedfiles