spring:
  mvc:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
  devtools:
    livereload:
      enabled: true
  datasource:
    jndi-name: jdbc/rookie
    
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:  - classpath:mappers/*.xml
  
  
server:
  servlet:
    session:
      timeout: 180m

